# handles application dependencies and virtual environment

- name: install python system wide dependencies via apt
  apt:
    name: ['python3-venv', 'python3-pip', 'python3-psycopg2', 'libpq-dev', 'python3-dev']
    update_cache: yes
    state: present
  become: yes

- name: install system wide Poetry
  pip:
    name: poetry
    state: present

- name: install dependencies in venv using Poetry lock file
  shell: "cd {{ requirements_file_dir }}; /home/{{ deploy_user }}/.local/bin/poetry install --no-dev"
