# handles server protection and configuration

- include: logs.yml
- include: security.yml
- include: nginx.yml
- include: git.yml
- include: dependencies.yml
- include: django.yml
- include: wsgi.yml